"""Add NestTalkUserMatchHouse model

Revision ID: 59fa4de6b8ee
Revises: 0003_add_turn_count
Create Date: 2026-04-15 17:37:37.768077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59fa4de6b8ee'
down_revision: Union[str, None] = '0003_add_turn_count'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nest_talk_user_match_houses',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('house_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('preference_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('match_score', sa.Float(), nullable=False),
        sa.Column('match_reason', sa.String(500), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('is_notified', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('notified_at', sa.DateTime(), nullable=True),
        sa.Column('matched_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['house_id'], ['nest_talk_houses.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['preference_id'], ['nest_talk_user_preferences.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nest_talk_user_match_houses_house_id'), 'nest_talk_user_match_houses', ['house_id'], unique=False)
    op.create_index(op.f('ix_nest_talk_user_match_houses_is_read'), 'nest_talk_user_match_houses', ['is_read'], unique=False)
    op.create_index(op.f('ix_nest_talk_user_match_houses_matched_at'), 'nest_talk_user_match_houses', ['matched_at'], unique=False)
    op.create_index(op.f('ix_nest_talk_user_match_houses_preference_id'), 'nest_talk_user_match_houses', ['preference_id'], unique=False)
    op.create_index(op.f('ix_nest_talk_user_match_houses_user_id'), 'nest_talk_user_match_houses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nest_talk_user_match_houses_user_id'), table_name='nest_talk_user_match_houses')
    op.drop_index(op.f('ix_nest_talk_user_match_houses_preference_id'), table_name='nest_talk_user_match_houses')
    op.drop_index(op.f('ix_nest_talk_user_match_houses_matched_at'), table_name='nest_talk_user_match_houses')
    op.drop_index(op.f('ix_nest_talk_user_match_houses_is_read'), table_name='nest_talk_user_match_houses')
    op.drop_index(op.f('ix_nest_talk_user_match_houses_house_id'), table_name='nest_talk_user_match_houses')
    op.drop_table('nest_talk_user_match_houses')
    # ### end Alembic commands ###
